# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
                ('type_1', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=30)),
                ('address_local', models.CharField(max_length=60)),
                ('address_stream', models.CharField(max_length=60)),
                ('dimension_in', models.IntegerField()),
                ('dimension_out', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('num_layer', models.IntegerField(default=2)),
                ('lr', models.FloatField()),
                ('parameter', models.TextField()),
                ('time', models.IntegerField(default=0)),
                ('error_rate', models.FloatField()),
                ('description', models.CharField(max_length=400)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl_manage.Data')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl_manage.Category')),
            ],
        ),
    ]
