# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-31 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dl_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type_name',
            new_name='type_2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='address_local',
        ),
        migrations.RemoveField(
            model_name='data',
            name='address_stream',
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_name',
        ),
        migrations.RemoveField(
            model_name='learningmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='learningmodel',
            name='error_rate',
        ),
        migrations.RemoveField(
            model_name='learningmodel',
            name='parameter',
        ),
        migrations.AddField(
            model_name='data',
            name='data_file',
            field=models.FileField(default=1, upload_to='data/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='arg_params',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='aux_params',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='data_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='dimension_in',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='dimension_out',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='norm_para',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='num_batch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='num_iter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='num_unit',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='symbol',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='test_error',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='learningmodel',
            name='train_error',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dl_manage.Data'),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='time',
            field=models.FloatField(default=0.0),
        ),
    ]
