# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-31 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_manage', '0002_auto_20160531_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodel',
            name='arg_params',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='aux_params',
            field=models.BinaryField(null=True),
        ),
    ]
